name: Dependency Updater

on:
    schedule:
        # every day at 07:33
        - cron: '33 7 * * *'
    workflow_dispatch: null # allow manual trigger

jobs:
    update-vendors:
        runs-on: ubuntu-latest
        steps:
            - name: Yarn PnP Setup
              uses: Araxeus/setup-yarn-pnp-action@v1

            - name: Run vendor update
              uses: Araxeus/vendorfiles-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  package-manager: yarn
