name: Dependency Updater

on:
  schedule:
    # every day at 07:33
    - cron: "33 7 * * *"

jobs:
  # check "yarn peru:update" then open a pull request with the changes if any
  update-vendors:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      - name: Run peru:ci
        id: peru-ci
        run: |
          echo "PR_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$(yarn peru:ci)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # - name: TEST
      #   run: printf '${{ steps.peru-ci.outputs.PR_BODY }}'
      # - name: Show git status
      #   run: git status

      - name: Create Pull Request
        if: steps.peru-ci.outputs.PR_BODY != 0
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[peru-ci] Bump vendors"
          committer: "peru-ci[bot] <oaeben@gmail.com>"
          author: "peru-ci[bot] <oaeben@gmail.com>"
          branch: bump-vendors
          title: "[peru-ci] Bump vendors"
          body: '${{ steps.peru-ci.outputs.PR_BODY }}'
          delete-branch: true
          labels: dependencies, peru-ci
          reviewers: ${{ github.repository_owner }}
          assignees: ${{ github.repository_owner }}

  update-python-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1

      # required for pnp 23+ which is required by https://pip.pypa.io/en/stable/reference/installation-report/
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
          check-latest: true

      - name: show pip versions
        run: pip --version && yarn npip --version

      - name: Run python-deps upgrade
        id: python-deps
        run: |
          echo "PR_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$(yarn python-deps upgrade --ci)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # - name: TEST
      #   run: printf '${{ steps.python-deps.outputs.PR_BODY }}'
      # - name: Show git status
      #   run: git status

      - name: Create Pull Request
        if: steps.python-deps.outputs.PR_BODY != 0
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[python-deps] Bump python dependencies"
          committer: "python-deps[bot] <oaeben@gmail.com>"
          author: "python-deps[bot] <oaeben@gmail.com>"
          branch: bump-python-deps
          title: "[python-deps] Bump python dependencies"
          body: '${{ steps.python-deps.outputs.PR_BODY }}'
          delete-branch: true
          labels: dependencies, python-deps
          reviewers: ${{ github.repository_owner }}
          assignees: ${{ github.repository_owner }}
